import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import prettier from "prettier"

const root = fileURLToPath(new URL("../", import.meta.url))
const manifestPath = path.join(root, "src", "built-in-icons.json")
const generatedPath = path.join(root, "src", "built-in-icons.generated.ts")
const readmePath = path.join(root, "README.md")
const packagePath = path.join(root, "package.json")
const checkOnly = process.argv.includes("--check")

const registryNamePattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/
const exportNamePattern = /^[A-Za-z_$][A-Za-z0-9_$]*$/
const exactVersionPattern = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/
const startMarker = "<!-- built-in-icons:start -->"
const endMarker = "<!-- built-in-icons:end -->"

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, "utf8"))
}

function normalizeLineEndings(value) {
  return value.replace(/\r\n?/g, "\n")
}

function compareAscii(left, right) {
  return left < right ? -1 : left > right ? 1 : 0
}

function validateManifest(value) {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new TypeError("src/built-in-icons.json must contain an object")
  }

  const entries = Object.entries(value).sort(([left], [right]) => compareAscii(left, right))
  if (entries.length === 0) throw new Error("built-in icon manifest must not be empty")

  for (const [alias, exportName] of entries) {
    if (!registryNamePattern.test(alias)) {
      throw new Error(`invalid built-in icon alias: ${JSON.stringify(alias)}`)
    }
    if (typeof exportName !== "string" || !exportNamePattern.test(exportName)) {
      throw new Error(`invalid Lucide export for ${alias}: ${JSON.stringify(exportName)}`)
    }
  }

  return entries
}

function renderReadmeList(names) {
  const lines = []
  let line = ""
  for (const name of names) {
    const candidate = line.length === 0 ? name : `${line}  ${name}`
    if (candidate.length > 88 && line.length > 0) {
      lines.push(line)
      line = name
    } else {
      line = candidate
    }
  }
  if (line.length > 0) lines.push(line)
  return lines.join("\n")
}

function replaceReadmeBlock(readme, names) {
  const start = readme.indexOf(startMarker)
  const end = readme.indexOf(endMarker)
  if (start < 0 || end < 0 || end < start) {
    throw new Error(`README.md must contain ${startMarker} and ${endMarker}`)
  }

  const replacement = `${startMarker}\n\n\`\`\`text\n${renderReadmeList(names)}\n\`\`\`\n\n${endMarker}`
  return readme.slice(0, start) + replacement + readme.slice(end + endMarker.length)
}

const entries = validateManifest(readJson(manifestPath))
const names = entries.map(([name]) => name)
const exports = [...new Set(entries.map(([, exportName]) => exportName))].sort(compareAscii)
const packageJson = readJson(packagePath)
const lucideVersion = packageJson.dependencies?.["lucide-preact"]
if (typeof lucideVersion !== "string" || !exactVersionPattern.test(lucideVersion)) {
  throw new Error("package.json must pin lucide-preact to one exact version")
}

const generatedSource = `// This file is generated by scripts/generate-icons.mjs. Do not edit it by hand.\nimport {\n${exports
  .map((name) => `  ${name},`)
  .join("\n")}\n} from "lucide-preact"\n\nexport const builtInLucideIcons = {\n${entries
  .map(([alias, exportName]) => `  ${JSON.stringify(alias)}: ${exportName},`)
  .join(
    "\n",
  )}\n} as const\n\nexport type BuiltInIconName = keyof typeof builtInLucideIcons\n\nexport const builtInIconNames = Object.freeze(\n  Object.keys(builtInLucideIcons) as BuiltInIconName[],\n)\n\nexport const lucidePackageVersion = ${JSON.stringify(lucideVersion)}\n`

const prettierConfig = (await prettier.resolveConfig(generatedPath)) ?? {}
const expectedGenerated = normalizeLineEndings(
  await prettier.format(generatedSource, {
    ...prettierConfig,
    filepath: generatedPath,
  }),
)
const currentReadme = normalizeLineEndings(fs.readFileSync(readmePath, "utf8"))
const expectedReadme = replaceReadmeBlock(currentReadme, names)

const stale = []
const currentGenerated = fs.existsSync(generatedPath)
  ? normalizeLineEndings(fs.readFileSync(generatedPath, "utf8"))
  : null
if (currentGenerated !== expectedGenerated) {
  stale.push(path.relative(root, generatedPath))
}
if (currentReadme !== expectedReadme) stale.push(path.relative(root, readmePath))

if (checkOnly) {
  if (stale.length > 0) {
    console.error(`Generated icon files are stale: ${stale.join(", ")}`)
    console.error("Run npm run icons:generate")
    process.exit(1)
  }
  console.log(`Built-in icon registry is synchronized (${entries.length} icons)`)
  process.exit(0)
}

fs.writeFileSync(generatedPath, expectedGenerated)
if (currentReadme !== expectedReadme) fs.writeFileSync(readmePath, expectedReadme)
console.log(`Generated ${entries.length} built-in icons for lucide-preact ${lucideVersion}`)
