// This file is generated by scripts/generate-icons.mjs. Do not edit it by hand.
import {
  BookOpen,
  CodeXml,
  Coffee,
  Container,
  Cpu,
  Database,
  FileCode,
  GitBranch,
  Globe,
  Layers,
  Network,
  Shield,
  Terminal,
} from "lucide-preact"

export const builtInLucideIcons = {
  "book-open": BookOpen,
  "code-2": CodeXml,
  coffee: Coffee,
  container: Container,
  cpu: Cpu,
  database: Database,
  "file-code-2": FileCode,
  "git-branch": GitBranch,
  globe: Globe,
  layers: Layers,
  network: Network,
  shield: Shield,
  terminal: Terminal,
} as const

export type BuiltInIconName = keyof typeof builtInLucideIcons

export const builtInIconNames = Object.freeze(
  Object.keys(builtInLucideIcons) as BuiltInIconName[],
)

export const lucidePackageVersion = "1.25.0"
