// This file is generated by scripts/generate-icons.mjs. Do not edit it by hand.
import {
  BookOpen,
  Calendar1,
  CodeXml,
  Coffee,
  Container,
  Cpu,
  Database,
  FileCode,
  FileQuestionMark,
  GitBranch,
  Globe,
  Layers,
  Network,
  NotebookPen,
  Shield,
  Terminal,
  UserGroup,
} from "lucide-preact"

export const builtInLucideIcons = {
  "book-open": BookOpen,
  "calendar-1": Calendar1,
  "code-2": CodeXml,
  coffee: Coffee,
  container: Container,
  cpu: Cpu,
  database: Database,
  "file-code-2": FileCode,
  "file-question-mark": FileQuestionMark,
  "git-branch": GitBranch,
  globe: Globe,
  layers: Layers,
  network: Network,
  "notebook-pen": NotebookPen,
  shield: Shield,
  terminal: Terminal,
  "user-group": UserGroup,
} as const

export type BuiltInIconName = keyof typeof builtInLucideIcons

export const builtInIconNames = Object.freeze(Object.keys(builtInLucideIcons) as BuiltInIconName[])

export const lucidePackageVersion = "1.46.0"
